name: GoTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          passowrd: ${{ secrets.DOCKER_PASSWORD }}
          repository: personal/pokemon-api
          tags: latest, ${{ github.run_number }}
